# Generated by Django 3.1.3 on 2022-02-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('car_num', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField()),
            ],
        ),
    ]
