# Generated by Django 4.0.2 on 2022-02-04 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='HelloWorld',
        ),
    ]
