# Generated by Django 3.1.3 on 2022-02-04 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruit',
            name='create_date',
        ),
    ]
