# Generated by Django 3.1.3 on 2022-02-04 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_remove_recruit_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
