# Generated by Django 3.1.3 on 2022-02-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_recruit_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='max_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='present_num',
            field=models.IntegerField(),
        ),
    ]
