# Generated by Django 3.1.3 on 2022-02-04 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruitment', '0004_auto_20220204_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='voter',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='max_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='present_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
