# Generated by Django 3.1.3 on 2022-02-04 13:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruitment', '0005_auto_20220204_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruit',
            name='voter',
        ),
        migrations.RemoveField(
            model_name='recruit',
            name='present_num',
        ),
        migrations.AddField(
            model_name='recruit',
            name='present_num',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
