# Generated by Django 3.1.3 on 2022-02-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_auto_20220204_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruit',
            name='present_num',
        ),
        migrations.AddField(
            model_name='recruit',
            name='present_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
