# Generated by Django 3.1.3 on 2022-02-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_auto_20220205_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='present_num',
            field=models.PositiveIntegerField(),
        ),
    ]
